# Numpy Basic Operations

In [1]:
import numpy as np

In [2]:
my_arr = np.array([[5,6,8,9]], dtype= np.int32)

In [3]:
my_arr

array([[5, 6, 8, 9]], dtype=int32)

In [4]:
my_arr.shape

(1, 4)

In [5]:
my_arr.dtype

dtype('int32')

In [6]:
my_arr[0,1]

6

# Numpy Array Creation

In [7]:
listarray = np.array([[1,2,3], [4,5,6]])
listarray

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
rng = np.arange(20)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
lspace = np.linspace(1, 100, 20)  # break down from 1 to 100 in 20 elements
lspace

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [11]:
emp = np.empty((5,5))
emp

array([[2.25966170e-316, 0.00000000e+000, 9.82157975e+252,
        8.89489936e+252, 6.01346954e-154],
       [6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
        9.08366793e+223, 1.14177168e+243],
       [2.45126797e+198, 1.06083187e-153, 2.35625393e+251,
        6.01334511e-154, 6.01347002e-154],
       [6.01347002e-154, 6.01347002e-154, 1.88556770e+122,
        4.96820036e+180, 6.80600993e+212],
       [1.10317376e+217, 1.19490107e+190, 2.06642651e+161,
        5.44760669e-109, 0.00000000e+000]])

In [12]:
emp_like = np.empty_like(lspace)  # more like copy array
emp_like

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [13]:
identity_matrix = np.identity(5)  # identity matrix
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [15]:
arr = arr.reshape(3,33)  # Breaks down into more col and rows
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [16]:
arr = arr.ravel()  # fix back to 1d array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [17]:
ar = np.arange(1, 10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ar = ar.reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
ar.sum(axis=0)  # sum of the first axis

array([12, 15, 18])

In [20]:
ar.T  # transpose matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
ar.ndim  # num of dimensions

2

In [22]:
ar.nbytes  # total bytes occupied in the memory

72

In [23]:
# ar.dtype = np.int8  # change dtype

In [24]:
ar.dtype

dtype('int64')

In [25]:
arr_1 = np.array([1,2,3,45,6])

In [26]:
arr_1.argmax()  # returns the index of the largest element

3

In [27]:
arr_1.argmin()  # smalles element index

0

In [28]:
arr_1.argsort()  # returns the array of sorted indexes for the array

array([0, 1, 2, 4, 3])

In [29]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
ar.argmax()

8

In [31]:
ar.argmin()

0

In [32]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [33]:
ar.argmax(axis=0)

array([2, 2, 2])

In [34]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [35]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

# Mathematical Operations

In [36]:
ar_2 = ar.T
ar_2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
ar + ar_2

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [38]:
ar * ar_2

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [39]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [40]:
np.dot(ar, ar_2)  # Matrix Multiplication

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.where(ar > 5)  # (x, y) from x - array1, y - array2 . 1,2 - 2,0 ....

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [43]:
np.count_nonzero(ar)

9

In [44]:
ar.sum()

45

In [45]:
ar.max()

9

In [46]:
ar.min()

1

In [47]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [48]:
import sys

In [49]:
py_arr = [1,2,3,4]

In [50]:
np_arr = np.array(py_arr)

In [51]:
sys.getsizeof(1) * len(py_arr)

112

In [52]:
np_arr.itemsize * np_arr.size

32